backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/media
public_folder: /media
collections:
  - name: "index" # Used in routes, e.g., /admin/collections/blog
    label: "Home page content" # Used in the UI
    folder: "content" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "index" # Filename template, e.g., YYYY-MM-DD-title.md
      # - {label: "Body", name: "body", widget: "markdown"}
    widget: "object"
    fields: # The fields for each document, usually in front matter
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Main title", name: "mainTitle", widget: "string"}
      - {label: "Info text", name: "infoText", widget: "string"}
      - {label: "Analytics image", name: "analyticsImage", widget: "image"}
      - label: "Quote"
        name: "quote"
        widget: "object"
        collapsed: true
        fields:
          - {label: "Quote text", name: "quoteText", widget: "string"}
          - {label: "Author", name: "quoteAuthor", widget: "string"}
